WebTruyen/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using WebTruyen.Models;

namespace WebTruyen.Components
{
    public class NavigationMenuViewComponent: ViewComponent
    {
        private readonly ITruyenRepository repository;

        public NavigationMenuViewComponent(ITruyenRepository repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke()
        {
            return View(repository.Truyens.Select(x=>x.TheLoai).Distinct().OrderBy(x=>x));
        }
    }
}

WebTruyen/Controllers/TruyenController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using WebTruyen.Models;
using WebTruyen.Models.ViewModels;

namespace WebTruyen.Controllers
{
    public class TruyenController : Controller
    {
        private readonly ITruyenRepository truyenRepository;
        public TruyenController(ITruyenRepository _truyenRepository)
        {
            truyenRepository = _truyenRepository;
        }
        public ViewResult List(string theloai)
        {
            return View(new TruyenListViewModel()
            {
                Truyens = truyenRepository.Truyens.Where(p=>theloai==null||p.TheLoai==theloai).OrderBy(p=>p.TruyenId),
            });
        }
        public IActionResult Details(int truyenId)
        {
            return View(truyenRepository.Truyens.FirstOrDefault(p=>p.TruyenId==truyenId));
        }

        public ViewResult searchName(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                return View(new TruyenListViewModel()
                {
                    Truyens = truyenRepository.Truyens.Where(p=>p.TenTruyen.Contains(name)).OrderBy(p=>p.TruyenId),
                });
            }
            else
            {
                return View(new TruyenListViewModel()
                {
                    Truyens = truyenRepository.Truyens.ToList(),
                });
            }
        }
    }
}

WebTruyen/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="~/lib/jquery/jquery.js"></script>
</head>
<body>
    <div class="d-flex justify-content-center navbar navbar-light bg-light" role="navigation">
        <p class="text-white w-75" style="font-size:xx-large">Moon Cyber Novel</p>
    </div>
    <div class="row m-1 p-1">
        <div class="col-12">
            <div class="align-content-center">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>

WebTruyen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <div class="container-fluid">
            <a class="navbar-brand p-2" href="#">
                <p class="text-white w-75" style="font-size:xx-large">Moon Cyber Novel</p>
            </a>
            <form asp-controller="Truyen" asp-action="searchName">
                <p>
                    <input type="text" name="name" />
                    <input type="submit" value="Tìm Truyện" />
                </p>
            </form>
        </div>
        
    </nav>
    <div class="row p-1 m-1">
        <div id="theloai" class="col-2">
            @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>